name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Build or create placeholder
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build
          else
            mkdir -p dist
            cat > dist/index.html <<'HTML'
            <!doctype html>
            <html>
              <head>
                <meta charset='utf-8'>
                <meta name='viewport' content='width=device-width, initial-scale=1'>
                <title>meena-kannan-fullstack</title>
                <style>
                  body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:720px;margin:4rem auto;padding:0 1rem;line-height:1.6}
                  h1{margin-bottom:.5rem}
                  code{background:#f5f5f5;padding:.2rem .4rem;border-radius:4px}
                </style>
              </head>
              <body>
                <h1>Deployment initialized</h1>
                <p>Your GitHub Pages workflow is active. Push your app files to the <code>main</code> branch to build and publish.</p>
              </body>
            </html>
            HTML
          fi
          touch dist/.nojekyll
          # SPA fallback for GitHub Pages
          cp dist/index.html dist/404.html || true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4